#!/bin/bash

set -o errexit

function usage
{
    echo "Usage: ./build [option]"
    echo ""
    echo "Option:"
    echo "    linux/amd64"
    echo "    windows/amd64"
    echo ""
}

case "$1" in
    "")
        # depends on current env
        ;;
    linux/amd64)
        GOOS=linux
        GOARCH=amd64
        ;;
    windows/amd64)
        GOOS=windows
        GOARCH=amd64
        ;;
    -h|--help)
        usage
        exit 1
        ;;
    *)
        echo "'$1': undefined option"
        echo ""
        usage
        exit 1
        ;;
esac

GIT_COUNT=$(git rev-list HEAD --count)
GIT_COMMIT=$(git log --pretty=format:"%h" -n 1 | tail -n 1)

GOBUILD_LDFLAGS="-X main.version=1.${GIT_COUNT}.${GIT_COMMIT} -extldflags -static"

GOOS=${GOOS} GOARCH=${GOARCH} go build -ldflags "${GOBUILD_LDFLAGS} -s -w" -o output/dsdd cmd/dsdd/dsdd.go
GOOS=${GOOS} GOARCH=${GOARCH} go build -ldflags "${GOBUILD_LDFLAGS}" -o output/dsdd.debug cmd/dsdd/dsdd.go
